version: '3.8'

services:
  app:
    build: .
    container_name: stock_pipeline_api
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
    restart: always